# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="murilasso"

ENABLE_CORRECTION="true"

plugins=(git osx terminalapp rbenv)

source $ZSH/oh-my-zsh.sh

zstyle ':completion:*' special-dirs true

alias gall='git add --all && git status'
alias rspec='nocorrect rspec'
alias gdw='git diff --color-words'
alias gsh='git stash'
alias gshp='git stash pop'
alias gpom='git pull origin master'
alias gdm='git diff master'
alias gf='git fetch'
alias stat='stat -x'
alias rspec='nocorrect rspec'

export BUNDLER_EDITOR='subl'

export PATH=$PATH:"/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/sm/bin:/opt/sm/pkg/active/bin:/opt/sm/pkg/active/sbin:/usr/local/sbin"
export PATH=$PATH:/usr/texbin
export PATH=$PATH:/usr/local/octave/3.8.0/bin/
export PATH=$PATH:$HOME/bin

# Go
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

# rbenv
eval "$(rbenv init - zsh)"

# fix locale issues when connecting to Linux machines via SSH
export LANG="en_US"
export LC_ALL=$LANG.UTF-8
